<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        // Seed categories
        DB::table('categories')->insert([
            [
                'name' => 'خدمات صيانة المنازل',
                'name_en' => 'Home Maintenance Services',
                'description' => 'خدمات صيانة وإصلاح المنازل',
                'icon' => 'fas fa-home',
                'color' => '#e3f2fd',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'خدمات التنظيف',
                'name_en' => 'Cleaning Services',
                'description' => 'خدمات التنظيف الشامل',
                'icon' => 'fas fa-broom',
                'color' => '#fce4ec',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'النقل والخدمات اللوجستية',
                'name_en' => 'Transportation & Logistics',
                'description' => 'خدمات النقل والشحن',
                'icon' => 'fas fa-truck',
                'color' => '#fff3e0',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'خدمات السيارات',
                'name_en' => 'Automotive Services',
                'description' => 'صيانة وإصلاح السيارات',
                'icon' => 'fas fa-car',
                'color' => '#e8f5e8',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'خدمات طارئة (عاجلة)',
                'name_en' => 'Emergency Services',
                'description' => 'خدمات الطوارئ العاجلة',
                'icon' => 'fas fa-exclamation-triangle',
                'color' => '#ffebee',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'خدمات الأسر والعائلات',
                'name_en' => 'Family Services',
                'description' => 'خدمات العائلات والأطفال',
                'icon' => 'fas fa-users',
                'color' => '#f3e5f5',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'خدمات تقنية',
                'name_en' => 'Technical Services',
                'description' => 'خدمات تقنية ومعلوماتية',
                'icon' => 'fas fa-laptop',
                'color' => '#e0f7fa',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'خدمات الحديقة',
                'name_en' => 'Garden Services',
                'description' => 'خدمات الحدائق والزراعة',
                'icon' => 'fas fa-seedling',
                'color' => '#e8f5e8',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        // Seed task types
        DB::table('task_types')->insert([
            // Category 1: خدمات صيانة المنازل
            [
                'name' => 'صيانة السباكة',
                'name_en' => 'Plumbing Maintenance',
                'category_id' => 1,
                'description' => 'إصلاح وصيانة أنظمة السباكة',
                'icon' => 'fas fa-wrench',
                'color' => '#e3f2fd',
                'price_range' => '50-200 دينار تونسي',
                'duration' => '1-3 ساعات',
                'difficulty' => 'medium',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'صيانة الكهرباء',
                'name_en' => 'Electrical Maintenance',
                'category_id' => 1,
                'description' => 'إصلاح وصيانة الأنظمة الكهربائية',
                'icon' => 'fas fa-bolt',
                'color' => '#fff3e0',
                'price_range' => '80-300 دينار تونسي',
                'duration' => '2-4 ساعات',
                'difficulty' => 'hard',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'صيانة التكييف',
                'name_en' => 'AC Maintenance',
                'category_id' => 1,
                'description' => 'صيانة أجهزة التكييف والتبريد',
                'icon' => 'fas fa-snowflake',
                'color' => '#e0f7fa',
                'price_range' => '100-400 دينار تونسي',
                'duration' => '2-3 ساعات',
                'difficulty' => 'medium',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Category 2: خدمات التنظيف
            [
                'name' => 'تنظيف عام للمنزل',
                'name_en' => 'General House Cleaning',
                'category_id' => 2,
                'description' => 'تنظيف شامل للمنزل',
                'icon' => 'fas fa-broom',
                'color' => '#fce4ec',
                'price_range' => '80-120 دينار تونسي',
                'duration' => '3-4 ساعات',
                'difficulty' => 'easy',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'تنظيف السجاد',
                'name_en' => 'Carpet Cleaning',
                'category_id' => 2,
                'description' => 'تنظيف وغسيل السجاد والموكيت',
                'icon' => 'fas fa-brush',
                'color' => '#f3e5f5',
                'price_range' => '50-100 دينار تونسي',
                'duration' => '1-2 ساعة',
                'difficulty' => 'medium',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Category 3: النقل والخدمات اللوجستية
            [
                'name' => 'نقل أثاث',
                'name_en' => 'Furniture Moving',
                'category_id' => 3,
                'description' => 'نقل الأثاث والممتلكات',
                'icon' => 'fas fa-truck',
                'color' => '#fff3e0',
                'price_range' => '100-300 دينار تونسي',
                'duration' => '2-4 ساعات',
                'difficulty' => 'medium',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'نقل سريع',
                'name_en' => 'Express Delivery',
                'category_id' => 3,
                'description' => 'نقل سريع للطرود والوثائق',
                'icon' => 'fas fa-shipping-fast',
                'color' => '#e8f5e8',
                'price_range' => '20-50 دينار تونسي',
                'duration' => '30-60 دقيقة',
                'difficulty' => 'easy',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'نقل طويل المدى',
                'name_en' => 'Long Distance Moving',
                'category_id' => 3,
                'description' => 'نقل لمسافات طويلة',
                'icon' => 'fas fa-route',
                'color' => '#f3e5f5',
                'price_range' => '200-500 دينار تونسي',
                'duration' => '4-8 ساعات',
                'difficulty' => 'hard',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Category 5: خدمات طارئة (عاجلة)
            [
                'name' => 'صيانة مكيف هواء',
                'name_en' => 'Air Conditioner Maintenance',
                'category_id' => 5,
                'description' => 'صيانة وتنظيف أجهزة التكييف',
                'icon' => 'fas fa-snowflake',
                'color' => '#e3f2fd',
                'price_range' => '100-300 دينار تونسي',
                'duration' => '2-3 ساعات',
                'difficulty' => 'medium',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'تنظيف مكيف هواء',
                'name_en' => 'Clean Air Conditioner',
                'category_id' => 5,
                'description' => 'تنظيف أجهزة التكييف والفلاتر',
                'icon' => 'fas fa-broom',
                'color' => '#e3f2fd',
                'price_range' => '60-150 دينار تونسي',
                'duration' => '1-2 ساعة',
                'difficulty' => 'easy',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'إصلاح مكيف هواء',
                'name_en' => 'Repair Air Conditioner',
                'category_id' => 5,
                'description' => 'إصلاح أعطال أجهزة التكييف',
                'icon' => 'fas fa-wrench',
                'color' => '#e3f2fd',
                'price_range' => '150-500 دينار تونسي',
                'duration' => '2-4 ساعات',
                'difficulty' => 'hard',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'تركيب مكيف هواء',
                'name_en' => 'Install Air Conditioner',
                'category_id' => 5,
                'description' => 'تركيب أجهزة التكييف الجديدة',
                'icon' => 'fas fa-plus-circle',
                'color' => '#e3f2fd',
                'price_range' => '300-800 دينار تونسي',
                'duration' => '4-8 ساعات',
                'difficulty' => 'hard',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'إصلاح ثلاجة',
                'name_en' => 'Repair Refrigerator',
                'category_id' => 5,
                'description' => 'إصلاح أعطال الثلاجات وأجهزة التبريد',
                'icon' => 'fas fa-ice-cream',
                'color' => '#e3f2fd',
                'price_range' => '100-400 دينار تونسي',
                'duration' => '2-4 ساعات',
                'difficulty' => 'hard',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        // Seed sample user
        DB::table('users')->insert([
            'name' => 'مستخدم تجريبي',
            'phone' => '01000690805',
            'email' => 'demo@example.com',
            'password' => 'askary20',
            'user_type' => 'customer',
            'governorate' => 'تونس',
            'city' => 'تونس العاصمة',
            'district' => 'المركز',
            'membership_code' => '558206',
            'status' => 'active',
            'created_at' => now(),
            'updated_at' => now(),
        ]);
    }
};
